# Configuration file for Logitech F710 and Ubuntu 16.04/ROS kinetic
joy_node:
  dev: /dev/input/js0
  deadzone: 0.02
  autorepeat_rate: 20
  coalesce_interval: 0.01
  
teleop:
  default:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: cmd_vel
    deadman_buttons: [4]
    axis_mappings:
      -
        axis: 3
        target: linear.x
        scale: 0.8
      -
        axis: 2
        target: linear.y
        scale: 0.8
      -
        axis: 1
        target: linear.z
        scale: 0.8
      -
        axis: 0
        target: angular.z
        scale: 0.5
  teleoperation:
    type: topic
    message_type: std_msgs/Int8
    topic_name: mode
    deadman_buttons: [4]
    message_value:
      -
        target: data
        value: 0
  autonomous:
    type: topic
    message_type: std_msgs/Int8
    topic_name: mode
    deadman_buttons: [5]
    message_value:
      -
        target: data
        value: 1